news_sites:
  eltiempo:
    url: https://www.eltiempo.com
    queries:
      homepage_article_links : '.title-container a'
      article_body: '.modulos'
      article_title: '.titulo-principal-bk h1'
     
  elespectador:
    url: https://www.elespectador.com/noticias
    queries:
      homepage_article_links : '.node-title a'
      article_body: '.node-body'
      article_title: '.node-title h1'

  eluniversal:
    url: http://www.eluniversal.com.mx
    queries:
      homepage_article_links: '.field-content a'
      article_body: '.field-name-body'
      article_title: '.pane-content h1'
  elpais:
    url: https://elpais.com
    queries:
      homepage_article_links: '.articulo-titulo a'
      article_body: '.articulo-cuerpo'
      article_title: '.articulo-titulo'
  publimetro:
    url: https://www.publimetro.co/co
    queries:
      homepage_article_links : '.tit a' 
      article_body: '.article__main'
      article_title: 'article-header h1'
